---
title: "Mini Analysis for Lab Presentation"
author: "Noah Stetson"
format: html
editor: visual
---

## Mini Analysis for Lab Meeting on 26 October 2022

## Loading library

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(corrr)
library(psych)
library(irr)
```

## Loading datasets

```{r}
obs <- read_csv("~/Documents/GitHub/PigPersonality/Obs_Oct21_Clean.csv") # behavior observations
svy_24_Oct <- read_csv("~/Desktop/Dan_Oct24.csv") # survey data (just 7 surveys all from Dan)
meta <- read_csv("~/Documents/GitHub/PigPersonality/PigSample.csv") # meta data (pig demographics)
```

Put meta data into df based on pig id number

```{r}
obs_m <- inner_join(obs, meta, by = "PigID")
svy_m <- inner_join(svy_24_Oct, meta, by = "PigID")
```

# Preliminary Analyses

## Overview of Personality Scores

```{r}
# generate a table of each pig's personality scores (one from Dan's scoring, one from Tracey's score, and calculate and average)
```

## Internal Reliability

### Inter-item correlation

(correlations between test items)

```{r}
# Make DF with just test items
svy_items <- svy_24_Oct %>% select(14:48)

# Overall average inter-item correlation for all surveys completed (each pig has 2 surveys)
svy_items_corr <- svy_items %>% correlate() %>% colMeans(na.rm = TRUE) # Having trouble removing NA

work_svy_items_corr <- as.numeric(unlist(svy_items_corr))

work_svy_items_corr <- work_svy_items_corr %>% correlate() %>% colMeans(na.rm = TRUE)

mean(svy_items_corr)

data.frame(svy_items_corr %>% 
  ggplot(aes(x = svy_items_corr)) +
    geom_histogram(bins = 10, alpha = .5) +
    geom_vline(xintercept = mean(svy_items_corr), color = "dodger blue") +
    xlab("Mean inter-item correlation") +
    theme_minimal()
  
# ahh why can't I remove the nas'
```

### Inter-total correlation

(correlations between scores)

```{r}
# Make df with just scores
svy_scores <- svy_24_Oct %>% select(49:61)

svy_scores_corr <- svy_scores %>% correlate() %>% colMeans(na.rm = TRUE)  # Having trouble removing NA

mean(svy_scores_corr)

data.frame(svy_scores_corr %>% 
  ggplot(aes(x = svy_scores_corr)) +
    geom_histogram(bins = 10, alpha = .5) +
    geom_vline(xintercept = mean(svy_scores_corr), color = "dodger blue") +
    xlab("Mean inter-total correlation") +
    theme_minimal()
```

### Chronbach's alpha

```{r}
psych::alpha(svy_items)

psych::alpha(svy_items)$total$std.alpha #this gets the alpha value itself
```

### 
